- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - prepare-nodes

- name: Initialize control plane
  hosts: control
  become: true
  roles:
    - init-control
  
- name: Join worker nodes to the cluster
  hosts: workers
  become: true
  roles:
    - join-workers

- name: Wait for the cluster
  hosts: ansible1
  become: true
  roles:
    - wait   

- name: Wait until all nodes are Ready
  hosts: all
  become: true
  roles:
    - wait

- name : Install app
  hosts: ansible1
  become: true
  collections:
    - kubernetes.core
  roles:
    - install-app
