- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - prepare-nodes

- name: Initialize control plane
  hosts: control-plane
  become: true
  roles:
    - init-control
  
- name: Join worker nodes to the cluster
  hosts: worker1
  become: true
  roles:
    - join-workers
  

- name: Wait until all nodes are Ready
  hosts: all
  become: true
  roles:
    - wait

- name : Install app
  hosts: control-plane
  become: true
  collections:
    - kubernetes.core
  roles:
    - install-app
